### ISSUE TITLE
About SMS configuration settings

### ISSUE THREAD

**Issue by askaralimkndr** [tzsk/sms#1248]
How can I manually add configuration settings from here,

Sms::via('twilio')->send("this message")->to(['+9196*********'])->dispatch();

Twilio has Account SID, Auth Token, and Twilio number, instead of configuring config/sms.php
If I wanted to set it from the same chain, is it possible? if yes, please give me a short code for it.

Thank you

**Comment by tzsk** [comment]
Use Laravel Config Overloading. Before calling this line.
