### ISSUE TITLE
adding multi-lang document

### ISSUE THREAD

**Issue by khanzadimahdi** [tzsk/sms#15]
what's your opinion about adding `wiki` with multiple languages in this package?

**Comment by tzsk** [comment]
I'll be totally into that but I'll prefer GitHub pages to have multi language documentataion with docsify.

But the entire development community writes code in English. I don't think putting that much effort will do much good. So much work, so little benefit.

If you can get multiple languages done. I'll be more than happy to add it.

**Comment by khanzadimahdi** [comment]
that's okay.
