### ISSUE TITLE
textlocal configuration

### ISSUE THREAD

**Issue by socialpilgrim** [tzsk/sms#169]
## Detailed description

It is a request, I need textlocal configuration

## Context

I am using this for 1 of my client, so  I need configuration details.

How can it benefit other users?
Would help to all textlocal implementers
## Possible implementation

Centos, PHP 7.4, Mysql
http://290px.com/elearn/public/

**Comment by tzsk** [comment]
@socialpilgrim You don't need to install any dependency for TextLocal. You can configure it with the text local keys in `config/sms.php` file after you publish the config file.
