### ISSUE TITLE
store sms in db

### ISSUE THREAD

**Issue by vahidalvandi** [tzsk/sms#173]
hi
thank you for this good package . i need event after send sms then store sms in db .

**Comment by tzsk** [comment]
That sounds like a responsibility on the Application Code rather than a Package. You can can store the message that you are sending right from you are sending it.

```php
$sms = sms()->send("this message")->to(['Number 1', 'Number 2'])->dispatch();

// Now you can dispatch whatever event you like.
event(new MyCustomEvent($sms));
```

**Comment by vahidalvandi** [comment]
ok . but is better you add fire event after send sms internally . this way is easy

**Comment by tzsk** [comment]
@vahidalvandi You do realize this is not just a Laravel Specific package. One can also use this package if they are not using Laravel as well.

**Comment by vahidalvandi** [comment]
@tzsk  i will send pull request
