### ISSUE TITLE
use second driver in send false

### ISSUE THREAD

**Issue by vahidalvandi** [tzsk/sms#174]
same time gateway  is disable please add Ability in error sending use second driver

**Comment by tzsk** [comment]
@vahidalvandi I cannot understand what you are trying to say. Illformed sentence.

**Comment by vahidalvandi** [comment]
Imagine i send sms with default gateway  ... but default gateway is not working , how i can switch to another gateway automatically ??

**Comment by tzsk** [comment]
@vahidalvandi That's a business level code. Where you can do that with a try-catch block. Any package like this would give you the tools to send an SMS. It is up to the business logic how they want to implement it.
