### ISSUE TITLE
class does not exist

### ISSUE THREAD

**Issue by rahushakya** [tzsk/sms#198]
i have taken following steps:

1) composer require tzsk/sms
2) php artisan vendor:publish --tag=config
3) changes config file in config/sms.php

4) calling these codes in required controller gives error:

`<?php
namespace App\Http\Controllers;
use App\Helper\Reply;
use App\Http\Requests\Sms\SendVerificationCode;
use App\Http\Requests\Sms\VerifyOTPCode;
use App\Notifications\NewUser;
use App\Traits\SmsSettings;
use App\User;
use Illuminate\Http\Request;    
use Tzsk\Sms\Facades\Sms;

class VerifyMobileController extends Controller
{
    use SmsSettings;

    public function __construct()
    {
        parent::__construct();
        $this->setSmsConfigs();
    }

    public function sendVerificationCode(SendVerificationCode $request)
    {
          sms()->send("this message")->to(['9999999999'])->dispatch();
      }
}

OUTPUT:

{
    "message": "Class  does not exist",
    "exception": "ReflectionException",
    "file": "E:\\wamp\\www\\laravael_project\\vendor\\tzsk\\sms\\src\\SmsManager.php",
    "line": 153,
    "trace": [
        {
            "file": "E:\\wamp\\www\\laravael_project\\vendor\\tzsk\\sms\\src\\SmsManager.php",
            "line": 153,
            "function": "__construct",
            "class": "ReflectionClass",
            "type": "->"
        },
        {
            "file": "E:\\wamp\\www\\laravael_project\\vendor\\tzsk\\sms\\src\\SmsManager.php",
            "line": 69,
            "function": "validateDriver",
            "class": "Tzsk\\Sms\\SmsManager",
            "type": "->"
        },
        {
            "file": "E:\\wamp\\www\\laravael_project\\vendor\\tzsk\\sms\\src\\SmsManager.php",
            "line": 45,
            "function": "via",
            "class": "Tzsk\\Sms\\SmsManager",
            "type": "->"
        },
        {
            "file": "E:\\wamp\\www\\laravael_project\\vendor\\tzsk\\sms\\src\\Provider\\SmsServiceProvider.php",
         ......

        ................... so ON
`
please help me asap, i am stuck here
Thanks

**Comment by tzsk** [comment]
@rahushakya What is that `setSmsConfig()` method doing?

**Comment by rahushakya** [comment]
please ignore, not related to your code

**Comment by rahushakya** [comment]
mistakenly i put that, so sorry, can you see what i did wrong, i am facing this issue... "class not found"

**Comment by tzsk** [comment]
@rahushakya which Gateway are you using?

**Comment by rahushakya** [comment]
textlocal

**Comment by tzsk** [comment]
You're overriding the config incorrectly. The map key in the config doesn't match with the gateway name.

@rahushakya

**Comment by rahushakya** [comment]
> You're overriding the config incorrectly. The map key in the config doesn't match with the gateway name.
> 
> @rahushakya

why you closed this issue, still issue not solved yet brother

**Comment by tzsk** [comment]
@rahushakya Closed cause, it is not an issue with the Package, it is the issue with how you are writing code.

You can see the UnitTests as evidence of that.
