### ISSUE TITLE
Error trying to use the Nexmo provider

### ISSUE THREAD

**Issue by EmanueleCoppola** [tzsk/sms#20]
## Detailed description
I installed the client using composer, set up everything following the package documentation, but, when I run this line of code
`
    Sms::send("Test 123")->to(['*********', '*********'])->dispatch();
`
I get this error:
`
    Call to undefined method Nexmo\Application\Client::message()
`

Edit: from Whoops i can see that the error is thrown in file vendor/tzsk/sms/src/Drivers/Nexmo.php on line 50, but I really can't understand where the problem is, since there isn't any static call.

## Your environment
* Version used: PHP 7.2.1, Laravel 5.5.34
* Operating system and version: OSX 10.14.3

**Comment by tzsk** [comment]
Did you install the Nexmo SDK?

`composer require nexmo/client`

**Comment by EmanueleCoppola** [comment]
Yes, I installed it.
