### ISSUE TITLE
add some features to each driver if they support.

### ISSUE THREAD

**Issue by khanzadimahdi** [tzsk/sms#209]
Hi, what's your opinion about adding some features to each driver and a feature checking ability to the package?
for example, some SMS gateways can send bulk messages and some of them doesn't support bulk messages.
I can create the below syntax:

```php
Sms::via('gateway')->whenSupportsBulkMessage(
       function($sms){
            $sms->sendBulk("this message")->to(['Number 1', 'Number 2'])->dispatch();
       }
)->whenDoesntSupportBulkMessage(function($sms) {
       function($sms){
            $sms->send("this message")->to(['Number 1', 'Number 2'])->dispatch();
       }
})
```

or something like the below syntax:

```php
// check if given gateway supports bulk sending messages.
if (Sms::via('gateway')->supportsBulkMessage()) { 
       //
}
```

if I add this feature, would you merge it ?

**Comment by tzsk** [comment]
@khanzadimahdi Do we need different ways for each of them?

Can we not just bulk send them when recipient count is more than one?

**Comment by khanzadimahdi** [comment]
bulk send is an example! as you know sms gateways offer more features.
for example time-base messages or one-time read messages! or even sound messages!

i use `Kavehnegar` gateway , and it offers sms templates! sms template is a prepared message (like prepared sql query) and data can be passed only to it to be sent to recipients.

I want to add some interfaces for these features and also an ability to check if a feature exists in selected gateway or not.

would you merge it if i add these functionalities?
hmm, or i would fork and develop and improved version of this package in my repositories if you don't like these features!

**Comment by khanzadimahdi** [comment]
i close this issue and develop suggested features in another package because of your late answering.
