### ISSUE TITLE
laravel 6 support

### ISSUE THREAD

**Issue by khanzadimahdi** [tzsk/sms#25]
not support laravel 6 !
the below error has showed in composer:

- don't install illuminate/support v5.8.8|don't install laravel/framework v6.0.3
- don't install illuminate/support v5.8.9|don't install laravel/framework v6.0.3
- Installation request for laravel/framework (locked at v6.0.3, required as ^6.0) -> satisfiable by laravel/framework[v6.0.3].
- Installation request for tzsk/sms ^2.0 -> satisfiable by tzsk/sms[2.0.0, 2.0.1, 2.0.2].

**Comment by tzsk** [comment]
Resolved in `3.0.0`
