### ISSUE TITLE
how i can use queue in this package ?

### ISSUE THREAD

**Issue by vahidalvandi** [tzsk/sms#268]
please help me i saw notification but i dont now how i can use this

**Comment by tzsk** [comment]
@vahidalvandi See https://laravel.com/docs/8.x/notifications#queueing-notifications

**Comment by vahidalvandi** [comment]
i saw this , My problem is that how i can use without user notifiy `$user->notify(new InvoicePaid($invoice));`
i have array mobile number how  i can use notification SmsChannel

thank you

**Comment by tzsk** [comment]
@vahidalvandi you are not making any sense. If you want to send sms in a queue then just put your code in a Job class.

https://github.com/tzsk/sms#fire-usage

**Comment by tzsk** [comment]
Technically you don't use **QUEUE IN A PACKAGE**, you use a **PACKAGE IN YOUR QUEUE**.

**Comment by vahidalvandi** [comment]
please show with sample
