### ISSUE TITLE
Multiple Sender ID use case

### ISSUE THREAD

**Issue by mohdfayeem** [tzsk/sms#278]
As I've multiple sender ID in my textlocal account, I want to use these sender ID dynamically when sending SMS. How to achieve this with this package by using TextLocal as default SMS Gateway.
Thanks.

**Comment by tzsk** [comment]
@mohdfayeem 
In the `config/sms.php` file add another configuration for Text Local. And add a handler map for that custom driver to TextLocal class.

```php
'drivers' => [
  ...
  'backup' => [...]
  ...
],

'map' => [
  ...
  'backup' => \Tzsk\Sms\Drivers\Textlocal::class,
  ...
],

// Now send using 
Sms::via('backup')->send("Hello")->to([******])->dispatch();

```

**Comment by mohdfayeem** [comment]
Thanks for your help. It really helpful.

**Comment by nxmndr** [comment]
For the record, if one wants to have dynamic configuration that doesn't require to edit config, the Tzsk\Sms\Sms class accepts config as constructor parameter.

You need to create your own channel :
```
(new Sms($smsOptions))
    ->send($msg)
    ->to([$phone])
    ->dispatch();
```
You can them store your custom $smsOptions in the DB.
