### ISSUE TITLE
SNS message type - Transactional throwing an invalid message type error

### ISSUE THREAD

**Issue by Tiththa** [tzsk/sms#415]
![image](https://user-images.githubusercontent.com/24600191/117128374-f3c18380-adba-11eb-9aa6-6a8d5fd641b0.png)

I am using SNS and I have followed the installation guide. Messaging works well with the message type `Promotional` however when switched to `transactional`, it throws the aforementioned error.
```php
Sms::send("Your Code")->to(['Number 1'])->dispatch();
```
Tried to encode the `Message` attribute as a JSON object, but still threw the error. Any help would be greatly appreciated.

Using Laravel V7 with SMS version 5.2

**Comment by tzsk** [comment]
Change the config file there's a typo. It should be 'Transactional'
Not 'Tansactional'

**Comment by Tiththa** [comment]
What a rookie typo, my bad. Thanks for the help!
