### ISSUE TITLE
Selecting Number in controller

### ISSUE THREAD

**Issue by vahidtakro** [tzsk/sms#424]
Hello,
I was given two different numbers by my provider and I'm now trying to add the usage in my controller, in usage I can select which driver to send my message from, but there is no an option to select the number.

**Comment by tzsk** [comment]
@vahidtakro There is a way. Create 2 gateways with the same handler mapping. In the config file. Then you can change between them.

**Comment by vahidtakro** [comment]
> @vahidtakro There is a way. Create 2 gateways with the same handler mapping. In the config file. Then you can change between them.

It works! thanks a lot.
