### ISSUE TITLE
using event class?

### ISSUE THREAD

**Issue by vipin733** [tzsk/sms#5]
is it possible to use this package in event class?

**Comment by tzsk** [comment]
Yes. Perfectly Possible. And it's a good place if you have any event when you want to fire SMS.

**Comment by vipin733** [comment]
thanks dude for making this package I hope its support future version of laravel. I am going to use this in production

**Comment by tzsk** [comment]
Yes! It will. It will be updated along with Laravel Updates. If it does not support you will definitely find another Release which does.

**Comment by vipin733** [comment]
I hope u will thanks
