### ISSUE TITLE
No sms.php after php artisan vendor:publish

### ISSUE THREAD

**Issue by SapneshNaik** [tzsk/sms#6]
I required the package via composer, added the class to providers array and alias as stated in instructions. after that when I did `php artisan vendor:publish` I get no sms.php in my config folder.

## Context
I am running a laravel 5.4 project

**Comment by tzsk** [comment]
Firstly, Is there any errors throwing in the console?

Secondly, run: `php artisan vendor:publish --tag=config`

If that doesn't work out. Copy the config file into your config folder.

`vendor/tzsk/sms/src/Config/sms.php => config/sms.php`

**Comment by SapneshNaik** [comment]
No errors in console. I finally had to manually copy the config file from vendor directory.
