### ISSUE TITLE
conflict with laravel 9

### ISSUE THREAD

**Issue by masoudabdan** [tzsk/sms#627]
Hi . 
tzsk/sms has an error on upgrading laravel 8 to laravel 9 
that is "illuminate/support" dependency used in tzsk/sms and can not used in laravel 9.
please check yourself.

**Comment by tzsk** [comment]
You're right @masoudabdan v6.0 is not released yet for this package. That'll have the Laravel 9 support.

**Comment by tzsk** [comment]
Released Support for Laravel 9 in `v6.0.0`
