### ISSUE TITLE
please change default config 

### ISSUE THREAD

**Issue by vahidalvandi** [tzsk/sms#857]
'default' => env('SMS_DEFAULT', 'textlocal'),

**Comment by tzsk** [comment]
🤔 But why? 😂

**Comment by j3yzz** [comment]
I concur with @vahidalvandi 's perspective that delegating the responsibility of determining the appropriate driver to the .env file not only results in a more organized and streamlined coding process, but also promotes overall code clarity.

If you agree, I will open a pull request :)

**Comment by tzsk** [comment]
I disagree. 

When you install any Laravel package it comes with a suitable default.

For example scout comes with Algolia. Even the out of the box database comes with `mysql`, cache comes with `file`, logging comes with `stack`.

You might argue to change the default to something other than textlocal but there will always be a default.

**Comment by j3yzz** [comment]
I understand that we always need a default config.
But we can make this change:

`env('SMS_DRIVER', 'textlocal')`

If u see `app/cache.php`, is used this method :)

`'default' => env('CACHE_DRIVER', 'file')`

**Comment by tzsk** [comment]
Yes. I'm okay with that.

But that would be a breaking change and it should go with Laravel 10 update.

**Comment by tzsk** [comment]
Fixed in `v7.0.0`
