### ISSUE TITLE
send parameter in MelliPayamakPatern

### ISSUE THREAD

**Issue by m5kh6n77** [tzsk/sms#917]
Hello!
How to send bodyid and argument in MelliPayamakPatern?

**Comment by mohaphez** [comment]
Based on the code written for this driver
The first argument is chosen as the code pattern . 
 
For example if you write something like that, It will probably work 

`Sms::via('melipayamakpattern')->send("patterncode=123 \n arg1=name \n arg2=family")->to(['Number 1', 'Number 2'])->dispatch();`

I hope that helps

**Comment by m5kh6n77** [comment]
> Based on the code written for this driver The first argument is chosen as the code pattern .
> 
> For example if you write something like that, It will probably work
> 
> `Sms::via('melipayamakpattern')->send("patterncode=123 \n arg1=name \n arg2=family")->to(['Number 1', 'Number 2'])->dispatch();`
> 
> I hope that helps

@mohaphez  thankyou solved!
